### ISSUE TITLE
Zrób pracę inżynierską.

### ISSUE THREAD

**Issue by Barrus00** [norbertgrzenkowicz/engineerka#1]
Aktualnie repo jest dosyć pustawę.
Jeżeli ten projekt ma być Twoją pracą inżynierską, to rozważyłbym dodanie więcej kodu do katalogów + przydalby się jakiś dokładniejszy opis projektu.

**Comment by norbertgrzenkowicz** [comment]
Dziękuję za szczegółową analizę mojego projektu. Obecnie projekt jest na
etapie mocno wstępnym z czym dokładne opisy oraz celowość tego projektu
zostanie naznaczone w czasie przyszłym

pon., 18 paź 2021, 22:03 użytkownik Barrus ***@***.***>
napisał:

**Comment by Barrus00** [comment]
Dzisiaj mija rok od tego wpisu, czas podsumować postępy...
